# Based on:
# https://github.com/healthchecks/healthchecks/blob/master/docker/docker-compose.yml

services:
  db:
    image: docker.io/library/postgres:17.0
    container_name: healthchecks-postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD

  web:
    image: docker.io/healthchecks/healthchecks:v3.6
    container_name: healthchecks-web
    env_file:
        - .env
    environment:
      - DB=postgres
      - DB_NAME=$DB_NAME
      - DB_HOST=db
      - DB_PASSWORD=$DB_PASSWORD
    ports:
        - "4000:8000"
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        # - "2525:2525"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
