# Based on:
# https://github.com/healthchecks/healthchecks/blob/master/docker/docker-compose.yml

services:
  db:
    image: docker.io/library/postgres:17.5
    container_name: healthchecks-postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true

  web:
    image: docker.io/healthchecks/healthchecks:v3.10
    container_name: healthchecks-web
    env_file:
        - .env
    environment:
      - DB=postgres
      - DB_NAME=$DB_NAME
      - DB_HOST=db
      - DB_PASSWORD=$DB_PASSWORD
    ports:
        - "4000:8000"
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        # - "2525:2525"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+$
      # enable diun
      - diun.enable=true
