version: '3.3'

services:
  stirling-pdf:
    image: docker.io/frooodle/s-pdf:0.26.1
    container_name: pdf-stirling
    ports:
      - '2939:8080'
    volumes:
      - ./configs:/configs
      # - /location/of/trainingData:/usr/share/tessdata #Required for extra OCR languages
      # - /location/of/customFiles:/customFiles/
      # - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true
