version: '3.3'

services:
  stirling-pdf:
    image: docker.io/frooodle/s-pdf:0.24.3
    container_name: pdf-stirling
    ports:
      - '2939:8080'
    volumes:
      - ./configs:/configs
      # - /location/of/trainingData:/usr/share/tessdata #Required for extra OCR languages
      # - /location/of/customFiles:/customFiles/
      # - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
