server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: journal
  journal:
    max_age: 12h
    labels:
      job: systemd-journal
    path: /var/log/journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal__hostname']
      target_label: 'hostname'

# - job_name: docker
  # pipeline_stages:
    # - docker: {}
  # static_configs:
  # - labels:
      # job: docker
      # __path__: /var/lib/docker/containers/*/*-json.log

# - job_name: containers
  # static_configs:
  # - targets:
      # - localhost
    # labels:
      # job: containerlogs
      # __path__: /var/lib/docker/containers/*/*log

  # pipeline_stages:
  # - json:
      # expressions:
        # output: log
        # stream: stream
        # attrs:
  # - json:
      # expressions:
        # tag:
      # source: attrs
  # - regex:
      # expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      # source: tag
  # - timestamp:
      # format: RFC3339Nano
      # source: time
  # - labels:
      # tag:
      # stream:
      # image_name:
      # container_name:
      # image_id:
      # container_id:
  # - output:
      # source: output
