server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/**/*log
      __path_exclude__: /var/log/suricata/stats.log
      hostname: callisto

- job_name: journal
  journal:
    max_age: 12h
    labels:
      job: systemd-journal
    path: /var/log/journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal__systemd_user_unit']
      target_label: 'user_unit'
    - source_labels: ['__journal__hostname']
      target_label: 'hostname'
    - source_labels: ['__journal__transport']
      target_label: 'transport'
    - source_labels: ['__journal__syslog_identifier']
      target_label: 'syslog_identifier'
    - source_labels: ['__journal_container_name']
      target_label: 'container'
    - source_labels: ['__journal__pid']
      target_label: 'pid'
