version: '3'

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10.10.1
    restart: unless-stopped
    ports:
      - 8096:8096
    container_name: media-jellyfin
    volumes:
      - ~/Media/media-stack:/media
      - ./jellyfin/config:/config
      - ~/Media/media-stack/jellyfin/cache:/cache
      - ~/Media/media-stack/jellyfin/transcodes:/transcodes
      - ~/Media/media-stack/jellyfin/metadata:/metadata
    group_add:
      - "video"
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card0
    user: 1001:1001
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true


  navidrome:
    image: docker.io/deluan/navidrome:0.53.3
    container_name: media-navidrome
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_CONFIGFILE: "/data/navidrome.toml"
    volumes:
      - "./navidrome:/data"
      - "~/Media/media-stack/music:/music:ro"
    ports:
      - "4533:4533"
    user: 1001:1001
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  transmission-openvpn:
    image: docker.io/haugene/transmission-openvpn:5.3.1
    container_name: media-transmission-openvpn
    mem_limit: 2g
    memswap_limit: 4g
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
    volumes:
      - ~/Media/media-stack:/data
      - ./transmission:/etc/openvpn/custom
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - CREATE_TUN_DEVICE=false
      - PUID=1001
      - PGID=1001
    sysctls:
        - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - 9091:9091
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  # nzbget:
    # image: docker.io/linuxserver/nzbget:version-v21.1
    # restart: unless-stopped
    # container_name: media-nzbget
    # environment:
      # - PUID=1001
      # - PGID=1001
      # - TZ=Europe/Europe
    # volumes:
      # - ./nzbget:/config
      # - ~/Media/nzbget/downloads:/downloads
      # - ~/Media/completed:/downloads/completed
    # ports:
      # - 6789:6789

  radarr:
    image: docker.io/linuxserver/radarr:5.14.0
    container_name: media-radarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./radarr:/config
      - ~/Media/media-stack/movies:/movies
      - ~/Media/media-stack/shows:/tv
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 7878:7878
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  sonarr:
    image: docker.io/linuxserver/sonarr:4.0.10
    container_name: media-sonarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./sonarr:/config
      - ~/Media/media-stack/movies:/movies
      - ~/Media/media-stack/shows:/tv
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 8989:8989
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  bazarr:
    image: docker.io/linuxserver/bazarr:1.4.5
    container_name: media-bazarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./bazarr:/config
      - ~/Media/media-stack/movies:/movies
      - ~/Media/media-stack/shows:/tv
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 6767:6767
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  lidarr:
    image: docker.io/linuxserver/lidarr:2.7.1
    container_name: media-lidarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./lidarr:/config
      - ~/Media/media-stack/music:/music
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 8686:8686
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  prowlarr:
    image: docker.io/linuxserver/prowlarr:1.25.4
    container_name: media-prowlarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  readarr:
    image: docker.io/linuxserver/readarr:0.4.3-develop
    container_name: media-readarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./readarr:/config
      - ~/Media/media-stack/books:/books
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 8787:8787
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+-develop$
      # enable diun
      - diun.enable=true

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:2.17.01
    container_name: media-tdarr
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1001
      - PGID=1001
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=tdarr-node
    volumes:
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - ./tdarr/logs:/app/logs
      - ~/Media/media-stack/:/media
      - ~/Media/tdarr/cache/:/temp
    group_add:
      - "video"
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card0
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  ombi:
    image: ghcr.io/linuxserver/ombi:4.44.1
    container_name: media-ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./ombi:/config
    ports:
      - 3579:3579
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  jellystat-db:
    image: docker.io/library/postgres:17.0
    container_name: media-jellystat-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/Media/media-stack/jellystat/data:/var/lib/postgresql/data
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true

  jellystat:
    image: docker.io/cyfershepard/jellystat:1.1.0
    container_name: media-jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JWT_KEY}
    ports:
      - "4040:3000"
    volumes:
      - ~/Media/media-stack/jellystat/backup-data:/app/backend/backup-data
    depends_on:
      - jellystat-db
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  ersatz-tv:
    image: docker.io/jasongdove/ersatztv:v0.8.8-vaapi
    container_name: media-ersatz-tv
    ports:
      - "8409:8409"
    volumes:
      - ./ersatz-tv:/root/.local/share/ersatztv
      - ~/Media/media-stack:/media:ro
    depends_on:
      - jellyfin
    environment:
      TZ: 'Europe/Amsterdam'
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card0
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+-vaapi$
      # enable diun
      - diun.enable=true

  letterboxd-monitor:
    image: docker.io/screeny05/letterboxd-list-radarr:1.1.6
    container_name: media-letterboxd-monitor
    ports:
        - 5000:5000
    environment:
        - REDIS_URL=redis://redis:6379
    depends_on:
        - redis
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true


  redis:
    image: docker.io/library/redis:7.4.0
    container_name: media-redis
    restart: unless-stopped
    volumes:
      - media_redis:/data
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

volumes:
  media_redis:
    external: true
    name: media_redis
