version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    container_name: media-jellyfin
    volumes:
      - /home/leon/Media:/media
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
    networks:
      - proxied
    group_add:
      - "video"
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: media-transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/leon/Media:/data
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    sysctls:
        - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - 9091:9091

  radarr:
    image: linuxserver/radarr
    container_name: media-radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./radarr:/config
      - /home/leon/Media/movies:/movies
      - /home/leon/Media/shows:/tv
      - /home/leon/Media/downloads:/downloads
      - /home/leon/Media/completed:/data/completed
    ports:
      - 7878:7878

  sonarr:
    image: linuxserver/sonarr
    container_name: media-sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./sonarr:/config
      - /home/leon/Media/movies:/movies
      - /home/leon/Media/shows:/tv
      - /home/leon/Media/downloads:/downloads
      - /home/leon/Media/completed:/data/completed
    ports:
      - 8989:8989

  jackett:
    image: linuxserver/jackett
    container_name: media-jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./jackett:/config
      - /home/leon/Media/downloads:/downloads
    ports:
      - 9117:9117

  bazarr:
    image: linuxserver/bazarr
    container_name: media-bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./bazarr:/config
      - /home/leon/Media/movies:/movies
      - /home/leon/Media/shows:/tv
      - /home/leon/Media/downloads:/downloads
      - /home/leon/Media/completed:/data/completed
    ports:
      - 6767:6767

networks:
  proxied:
    external: true
    name: proxied
