version: '3'

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10.8.9
    restart: unless-stopped
    ports:
      - 8096:8096
    container_name: media-jellyfin
    volumes:
      - ~/Media/media-stack:/media
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
    group_add:
      - "video"
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    user: 1001:1001

  navidrome:
    image: docker.io/deluan/navidrome:0.49.3
    container_name: media-navidrome
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_CONFIGFILE: "/data/navidrome.toml"
    volumes:
      - "./navidrome:/data"
      - "~/Media/media-stack/music:/music:ro"
    ports:
      - "4533:4533"
    user: 1001:1001

  transmission-openvpn:
    image: docker.io/haugene/transmission-openvpn:4.3.2
    container_name: media-transmission-openvpn
    mem_limit: 2g
    memswap_limit: 4g
    restart: "no"
    cap_add:
      - NET_ADMIN
    volumes:
      - ~/Media/media-stack:/data
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - CREATE_TUN_DEVICE=false
      - PUID=1001
      - PGID=1001
    sysctls:
        - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - 9091:9091
    devices:
      - /dev/net/tun:/dev/net/tun

  # nzbget:
    # image: docker.io/linuxserver/nzbget:version-v21.1
    # restart: unless-stopped
    # container_name: media-nzbget
    # environment:
      # - PUID=1001
      # - PGID=1001
      # - TZ=Europe/Europe
    # volumes:
      # - ./nzbget:/config
      # - ~/Media/nzbget/downloads:/downloads
      # - ~/Media/completed:/downloads/completed
    # ports:
      # - 6789:6789

  radarr:
    image: docker.io/linuxserver/radarr:4.3.2
    container_name: media-radarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./radarr:/config
      - ~/Media/media-stack/movies:/movies
      - ~/Media/media-stack/shows:/tv
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 7878:7878

  sonarr:
    image: docker.io/linuxserver/sonarr:3.0.9
    container_name: media-sonarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./sonarr:/config
      - ~/Media/media-stack/movies:/movies
      - ~/Media/media-stack/shows:/tv
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 8989:8989

  jackett:
    image: docker.io/linuxserver/jackett:0.20.3063
    container_name: media-jackett
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./jackett:/config
      - ~/Media/media-stack/downloads:/downloads
    ports:
      - 9117:9117

  bazarr:
    image: docker.io/linuxserver/bazarr:1.1.4
    container_name: media-bazarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./bazarr:/config
      - ~/Media/media-stack/movies:/movies
      - ~/Media/media-stack/shows:/tv
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 6767:6767

  lidarr:
    image: docker.io/linuxserver/lidarr:1.0.2
    container_name: media-lidarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./lidarr:/config
      - ~/Media/media-stack/music:/music
      - ~/Media/media-stack/downloads:/downloads
      - ~/Media/media-stack/completed:/data/completed
    ports:
      - 8686:8686

  prowlarr:
    image: docker.io/linuxserver/prowlarr:1.1.3
    container_name: media-prowlarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
