version: '3'

services:
  server:
    image: codeberg.org/forgejo/forgejo:11.0.2
    restart: unless-stopped
    container_name: forgejo
    networks:
      - forgejo
    volumes:
      - ./forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3300:3000'
      - '222:22'
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

networks:
  forgejo:
    external: false
