version: '3'

services:
  grafana:
    image: docker.io/grafana/grafana-oss:12.1.0
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  loki:
    image: docker.io/grafana/loki:3.5.3
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ~/Media/loki/:/loki
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true
    # also:
    # - run:
    # docker plugin install grafana/loki-docker-driver:2.4.2 --alias loki --grant-all-permissions
    # - change default logging driver:
    # https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#change-the-default-logging-driver

  promtail:
    image: docker.io/grafana/promtail:3.5.3
    container_name: grafana-promtail
    volumes:
      - /var/log:/var/log
      - /run/log/journal:/run/log/journal
      - /etc/machine-id:/etc/machine-id
      - ./promtail:/etc/promtail
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana
    group_add:
      - 983 # systemd-journal group
    x-podman.gidmaps:
      - "+g983:@983" # map host systemd-journal group number to container
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  node-exporter:
    image: docker.io/prom/node-exporter:v1.9.1
    container_name: grafana-node-exporter
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - ./textfile_collector/prom/:/textfile_collector_files/
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/textfile_collector_files/'
    network_mode: host
    pid: host
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  blackbox-exporter:
    image: docker.io/prom/blackbox-exporter:v0.27.0
    container_name: grafana-blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/prometheus/blackbox.yml:ro
    command:
      - --config.file=/etc/prometheus/blackbox.yml
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  prometheus_podman_exporter:
    image: quay.io/navidys/prometheus-podman-exporter:v1.17.2
    container_name: grafana-prometheus-podman-exporter
    command: --collector.enhance-metrics
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock
    security_opt:
      - label=disable
    userns_mode: keep-id:uid=65534
    networks:
      - grafana
    ports:
      - 9882:9882
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  cloud-storage-usage:
    image: localhost/cloud-storage-usage
    container_name: cloud-storage-usage
    ports:
      9393:9393
    networks:
      - grafana

networks:
  grafana:
    external: false
    name: grafana

volumes:
  grafana-storage:
    external: true
    name: grafana-storage
  prometheus_data:
    external: true
    name: prometheus_data

# Disable adding contains to pods by default, since it conflicts with userns_mode.
# See https://github.com/containers/podman-compose/blob/main/docs/Extensions.md#custom-pods-management
x-podman:
    in_pod: false
