version: '3'

services:
  grafana:
    image: docker.io/grafana/grafana-oss:10.2.3
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  loki:
    image: docker.io/grafana/loki:2.9.3
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true
    # also:
    # - run:
    # docker plugin install grafana/loki-docker-driver:2.4.2 --alias loki --grant-all-permissions
    # - change default logging driver:
    # https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#change-the-default-logging-driver

  promtail:
    image: docker.io/grafana/promtail:2.9.1
    container_name: grafana-promtail
    volumes:
      - /var/log:/var/log
      - /run/log/journal:/run/log/journal
      - /etc/machine-id:/etc/machine-id
      - ./promtail:/etc/promtail
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  prometheus:
    image: docker.io/prom/prometheus:v2.49.1
    container_name: grafana-prometheus
    restart: unless-stopped
    command:
      - '--storage.tsdb.retention.time=30d'
    ports:
      - "9152:9090"
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  node-exporter:
    image: docker.io/prom/node-exporter:v1.7.0
    container_name: grafana-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  blackbox-exporter:
    image: docker.io/prom/blackbox-exporter:v0.24.0
    container_name: grafana-blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/prometheus/blackbox.yml:ro
    command:
      - --config.file=/etc/prometheus/blackbox.yml
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  prometheus_podman_exporter:
    # image: quay.io/navidys/prometheus-podman-exporter:v1.3.0
    image: localhost/prometheus-podman-exporter-fork
    container_name: grafana-prometheus-podman-exporter
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock
    security_opt:
      - label=disable
    userns:
      - keep-id
    user: "1000"

  cloud-storage-usage:
    image: localhost/cloud-storage-usage
    container_name: cloud-storage-usage
    ports:
      9393:9393
    networks:
      - grafana

  grafana-nginx-prometheus-exporter-leda:
    image: docker.io/nginx/nginx-prometheus-exporter:1.1
    container_name: grafana-nginx-prometheus-exporter-leda
    command: -nginx.scrape-uri=http://100.87.106.110:8080/stub_status
    ports:
      9113:9113
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true

  grafana-nginx-prometheus-exporter-callisto:
    image: docker.io/nginx/nginx-prometheus-exporter:1.1
    container_name: grafana-nginx-prometheus-exporter-callisto
    command: -nginx.scrape-uri=http://nginx:8080/stub_status -web.listen-address=:9114
    ports:
      9114:9114
    networks:
      - grafana
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true

networks:
  grafana:
    external: false
    name: grafana

volumes:
  grafana-storage:
    external: true
    name: grafana-storage
  prometheus_data:
    external: true
    name: prometheus_data
