version: '3'

services:
  loki:
    image: grafana/loki:2.4.2
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    # also:
    # - run:
    # docker plugin install grafana/loki-docker-driver:2.4.2 --alias loki --grant-all-permissions
    # - change default logging driver:
    # https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#change-the-default-logging-driver

  promtail:
    image: grafana/promtail:2.4.2
    container_name: grafana-promtail
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml

  prometheus:
    image: prom/prometheus:v2.33.3
    container_name: grafana-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: grafana-node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  grafana:
    image: grafana/grafana-oss:8.3.6
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000

networks:
  default:
    external: true
    name: proxied

volumes:
  grafana-storage:
    external: true
    name: grafana-storage
  prometheus_data:
    external: true
    name: prometheus_data
