version: '3'

services:
  loki:
    image: docker.io/grafana/loki:2.7.3
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - grafana
    # also:
    # - run:
    # docker plugin install grafana/loki-docker-driver:2.4.2 --alias loki --grant-all-permissions
    # - change default logging driver:
    # https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#change-the-default-logging-driver

  # promtail:
    # image: docker.io/grafana/promtail:2.7.3
    # container_name: grafana-promtail
    # volumes:
      # - /var/log:/var/log
      # - ./promtail:/etc/promtail
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    # command: -config.file=/etc/promtail/config.yml
    # networks:
      # - grafana

  prometheus:
    image: docker.io/prom/prometheus:v2.42.0
    container_name: grafana-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - grafana

  node-exporter:
    image: docker.io/prom/node-exporter:v1.5.0
    container_name: grafana-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - grafana

  blackbox-exporter:
    image: docker.io/prom/blackbox-exporter:v0.23.0
    container_name: grafana-blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/prometheus/blackbox.yml:ro
    command:
      - --config.file=/etc/prometheus/blackbox.yml
    networks:
      - grafana

  prometheus_podman_exporter:
    image: quay.io/navidys/prometheus-podman-exporter
    container_name: grafana-prometheus-podman-exporter
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock
    security_opt:
      - label=disable
    userns:
      - keep-id
    user: "1000"

  grafana:
    image: docker.io/grafana/grafana-oss:9.4.0-beta1
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - grafana

networks:
  grafana:
    external: false
    name: grafana

volumes:
  grafana-storage:
    external: true
    name: grafana-storage
  prometheus_data:
    external: true
    name: prometheus_data
