version: '3'

services:
  elasticsearch:
    image: docker.io/library/elasticsearch:8.12.2
    container_name: ids-elasticsearch
    restart: never
    # "If --memory-swap is set to the same value as --memory, and --memory is set to a positive integer, the container doesn't have access to swap"
    # https://docs.docker.com/config/containers/resource_constraints/#prevent-a-container-from-using-swap
    mem_limit: 8g
    memswap_limit: 8g
    environment:
      - discovery.type='single-node'
      - xpack.security.enabled='false'
    volumes:
      - ~/Media/intrusion-detection/data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ids
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  kibana:
    image: docker.io/library/kibana:8.12.2
    container_name: ids-kibana
    restart: unless-stopped
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - xpack.reporting.encryptionKey=${ENCRYPTION_KEY}
      - xpack.security.encryptionKey=${ENCRYPTION_KEY}
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - ids
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  filebeat:
    image: docker.io/elastic/filebeat:8.12.2
    container_name: ids-filebeat
    restart: unless-stopped
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/suricata.yml:/usr/share/filebeat/modules.d/suricata.yml
      - /var/log/suricata/eve.json:/var/log/suricata/eve.json:ro
    networks:
      - ids
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  evebox:
    image: docker.io/jasonish/evebox:0.18.0
    container_name: ids-evebox
    restart: unless-stopped
    ports:
      - "5636:5636"
    command: evebox server --no-auth -e http://elasticsearch:9200 --ecs --index filebeat
    networks:
      - ids
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

networks:
  ids:
    external: false
    name: ids
