version: '3'

services:
  rustypaste:
    image: ghcr.io/orhun/rustypaste/rustypaste:0.16.1
    container_name: rustypaste
    restart: unless-stopped
    # environment:
      # - RUST_LOG=debug
    env_file:
      - ./.env
    ports:
      - "7452:8000"
    volumes:
      - ./rustypaste_upload/:/app/upload
      - ./config.toml:/app/config.toml
