version: '3'

services:
  paste:
    image: localhost/shortpaste
    container_name: shortpaste
    restart: unless-stopped
    volumes:
      - ./pastes/shortpaste:/root/.shortpaste
      - ./favicon.ico:/usr/local/bin/shortpaste/static/favicon.ico
    environment:
      - SP_USERNAME=${USERNAME}
      - SP_PASSWORD=${PASSWORD}
      - SP_307_REDIRECT=1 # redirect directly instead of showing delay page
    ports:
      - 7452:8080

