version: '3'

services:

  synapse:
    image: docker.io/matrixdotorg/synapse:v1.137.0
    container_name: matrix-synapse
    restart: unless-stopped
    build:
        context: ../..
        dockerfile: docker/Dockerfile
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./config:/data
    depends_on:
      - db
    ports:
      - 8008:8008
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true
    networks:
      - grafana
      - matrix

  db:
    image: docker.io/library/postgres:17.6
    container_name: matrix-postgres
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # ensure the database gets created correctly
      # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - matrix
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true

  syncv3:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.19
    container_name: matrix-sliding-sync-proxy
    environment:
      - SYNCV3_SERVER=http://matrix-synapse:8008 # Destination homeserver
      - SYNCV3_SECRET=${SYNCV3_SECRET}
      - SYNCV3_DB=user=synapse dbname=syncv3 sslmode=disable password=${DB_PASSWORD} host=matrix-postgres # psql connection string
      - SYNCV3_BINDADDR=0.0.0.0:8009 # The interface and port to listen on
      - SYNCV3_PROM=:2112 # Enable Prometheus metrics
    ports:
      - 8009:8009
      - 2112:2112
    networks:
      - matrix
    depends_on:
      - db
      - synapse
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true


networks:
  grafana:
    external: true
  matrix:
    external: false
    name: matrix
