version: '3'

services:

  synapse:
    image: docker.io/matrixdotorg/synapse:v1.92.3
    container_name: matrix-synapse
    restart: unless-stopped
    build:
        context: ../..
        dockerfile: docker/Dockerfile
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./config:/data
    depends_on:
      - db
    ports:
      - 8008:8008
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true
    networks:
      - grafana

  db:
    image: docker.io/library/postgres:16.0
    container_name: matrix-postgres
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # ensure the database gets created correctly
      # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true

networks:
  grafana:
    external: true
