version: '3'

services:
  db:
    image: docker.io/library/postgres:15.4
    container_name: nextcloud-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWD}
      - POSTGRES_DB=nextcloud
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - nextcloud
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+$
      # enable diun
      - diun.enable=true


  redis:
    image: docker.io/library/redis:7.2.0
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - nextcloud_redis:/data
    networks:
      - nextcloud
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  nextcloud:
    image: docker.io/library/nextcloud:27.0.2-apache
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ./shared:/shared
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - nextcloud
    ports:
      - 6952:80
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+-apache$
      # enable diun
      - diun.enable=true

volumes:
  nextcloud:
    external: true
    name: nextcloud
  nextcloud_redis:
    external: true
    name: nextcloud_redis

networks:
  nextcloud:
    external: false
    name: nextcloud
