version: '3'

services:
  db:
    image: postgres:14.6
    container_name: nextcloud-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWD}
      - POSTGRES_DB=nextcloud
    volumes:
      - nextcloud_postgres:/var/lib/postgresql/data
    networks:
      - nextcloud

  redis:
    image: redis:7.0.7
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - nextcloud_redis:/data
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:stable-apache
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ./shared:/shared
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - nextcloud
    ports:
      - 80:80

volumes:
  nextcloud:
    external: true
    name: nextcloud
  nextcloud_postgres:
    external: true
    name: nextcloud_postgres
  nextcloud_redis:
    external: true
    name: nextcloud_redis

networks:
  nextcloud:
    external: false
    name: nextcloud
