version: "3.5"

services:
  # postgres:
    # image: docker.io/library/postgres:17.2
    # container_name: bookmarks-linkwarden-postgres
    # # restart: unless-stopped
    # env_file: .env
    # volumes:
      # - ./data:/var/lib/postgresql/data

  # linkwarden:
    # image: ghcr.io/linkwarden/linkwarden:v2.5.1
    # container_name: bookmarks-linkwarden
    # # restart: unless-stopped
    # env_file: .env
    # environment:
      # - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    # ports:
      # - 3002:3000
    # volumes:
      # - ./linkwarden_data:/data/data
    # depends_on:
      # - postgres

  karakeep-web:
    image: ghcr.io/karakeep-app/karakeep:0.23.2
    container_name: bookmarks-karakeep-web
    restart: unless-stopped
    volumes:
      - ./karakeep-data:/data
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://karakeep-meilisearch:7700
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
      DISABLE_SIGNUPS: "true"
    labels:
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$

  karakeep-chrome:
    image: docker.io/zenika/alpine-chrome:124
    container_name: bookmarks-karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    labels:
      # regular expression to filter tags
      - diun.include_tags=^\d+$

  karakeep-meilisearch:
    image: docker.io/getmeili/meilisearch:v1.13.3
    container_name: bookmarks-karakeep-meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./karakeep-meilisearch-data:/meili_data
    labels:
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
