version: '3'
services:
  znc:
    image: docker.io/library/znc:1.9.0
    container_name: znc
    restart: unless-stopped
    volumes:
      - ./.znc/:/znc-data
    ports:
      - 9396:9396
      - 9397:9397
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

