version: '3'
services:
  znc:
    image: docker.io/library/znc:1.8.2
    container_name: znc
    restart: unless-stopped
    volumes:
      - ./.znc/:/znc-data
    ports:
      - 9396:9396
      - 9397:9397

