version: '3.5'

services:
  tubearchivist:
    image: docker.io/bbilly1/tubearchivist:v0.4.11
    container_name: tubearchivist
    ports:
      - 8612:8000
    volumes:
      - ~/Media/tube-archivist/media:/youtube
      - ~/Media/tube-archivist/cache:/cache
    environment:
      - ES_URL=http://tubearchivist-elasticsearch:9200     # needs protocol e.g. http and port
      - REDIS_HOST=tubearchivist-redis          # don't add protocol
      - HOST_GID=1000
      - TA_HOST=${TA_HOST}
      - TA_USERNAME=${TA_USERNAME}
      - TA_PASSWORD=${TA_PASSWORD}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - TZ=Europe/Amsterdam
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - tubearchivist-elasticsearch
      - tubearchivist-redis
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  tubearchivist-redis:
    image: docker.io/redis/redis-stack-server:7.4.0-v1-x86_64
    container_name: tubearchivist-redis
    expose:
      - "6379"
    volumes:
      - tubearchivist-redis:/data
    depends_on:
      - tubearchivist-elasticsearch
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+-v\d+-x86_64$
      # enable diun
      - diun.enable=true

  tubearchivist-elasticsearch:
    image: docker.io/bbilly1/tubearchivist-es:8.14.3
    container_name: tubearchivist-elasticsearch
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"       # matching Elasticsearch password
      # - "ES_DISABLE_VERIFY_SSL=1"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - tubearchivist-elasticsearch:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

  tubearchivist-metrics:
    image: docker.io/bbilly1/tubearchivist-metrics:v0.0.1
    restart: unless-stopped
    container_name: tubearchivist-metrics
    environment:
      - "ES_PASSWORD=${ELASTIC_PASSWORD}"
      - "ES_URL=http://tubearchivist-elasticsearch:9200"
      - "LISTEN_PORT=9934"
      - "POLL_INTERVAL=60"
    ports:
      - 9934:9934
    depends_on:
      - tubearchivist-elasticsearch
    labels:
      # watch all tags
      - diun.watch_repo=true
      # maximum number of tags to watch
      - diun.max_tags=3
      # sort by semantical versioning order
      - diun.sort_tags=semver
      # regular expression to filter tags
      - diun.include_tags=^v\d+\.\d+\.\d+$
      # enable diun
      - diun.enable=true

volumes:
  tubearchivist-redis:
  tubearchivist-elasticsearch:
