version: '3'

services:
  nginx:
    image: docker.io/nginxinc/nginx-unprivileged:1.27.1
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/reverse-proxy-http.conf:/etc/nginx/sites-enabled/reverse-proxy.conf
      - ./config/local-http.conf:/etc/nginx/sites-enabled/local-http.conf
      - ./config/reverse-proxy-misc.conf:/etc/nginx/other-enabled/reverse-proxy.conf
      - ./letsencrypt/:/etc/letsencrypt/:ro
      - ./self_signed/certificates/:/etc/certificates/:ro
    ports:
      - "80:8080"
      - "443:4430"
      - "8448:8448"
    labels:
      # watch all tags
      - diun.watch_repo=true
        # maximum number of tags to watch
      - diun.max_tags=3
        # sort by semantical versioning order
      - diun.sort_tags=semver
        # regular expression to filter tags
      - diun.include_tags=^\d+\.\d+\.\d+$
        # enable diun
      - diun.enable=true
    networks:
      - grafana

networks:
  grafana:
    external: true
