global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "leda"
    static_configs:
    - targets: ["100.87.106.110:9100"]

  - job_name: "prometheus-podman-exporter"
    static_configs:
    - targets: ["prometheus_podman_exporter:9882"]

  - job_name: "cloud-storage-usage"
    scrape_interval: 1m
    static_configs:
      - targets: ["cloud-storage-usage:9393"]

  - job_name: "nginx-prometheus-exporter"
    static_configs:
      - targets: ["grafana-nginx-prometheus-exporter:9113"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cloud.lhax.xyz/
        - https://media.lhax.xyz/
        - https://music.lhax.xyz/
        - https://paper.lhax.xyz/
        - https://status.lhax.xyz/
        - https://rss.lhax.xyz/
        - https://znc.lhax.xyz/
        - https://lhax.xyz/
        - https://leongr.nl/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
