global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
    - targets: ["cadvisor:8080"]

  - job_name: "docker-exporter"
    static_configs:
    - targets: ["docker-exporter:9417"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cloud.lhax.xyz/
        - https://media.lhax.xyz/
        - https://paper.lhax.xyz/
        - https://status.lhax.xyz/
        - https://znc.lhax.xyz/
        - https://lhax.xyz/
        - https://io.lhax.xyz:5000
        - https://leongr.nl/
        - https://concertrack.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
