global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node-exporter-callisto"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "leda"
    static_configs:
    - targets: ["100.100.187.49:9100"]

  - job_name: "Lysithea node-exporter"
    static_configs:
    - targets: ["100.99.163.26:9100"]

  - job_name: "dia"
    static_configs:
    - targets: ["100.75.159.26:9100"]

  - job_name: "jupiter"
    static_configs:
      - targets: ["192.168.3.11:9100"]

  - job_name: "prometheus-podman-exporter"
    static_configs:
    - targets: ["prometheus_podman_exporter:9882"]

  - job_name: "cloud-storage-usage"
    scrape_interval: 1m
    static_configs:
      - targets: ["cloud-storage-usage:9393"]

  - job_name: "nginx-prometheus-exporter-leda"
    static_configs:
      - targets: ["100.100.187.49:9113"]

  - job_name: "nginx-prometheus-exporter-dia"
    static_configs:
      - targets: ["100.75.159.26:9113"]

  - job_name: "nginx-prometheus-exporter-callisto"
    static_configs:
      - targets: ["grafana-nginx-prometheus-exporter-callisto:9114"]

  - job_name: "nginx-prometheus-exporter-lysithea"
    static_configs:
      - targets: ["100.99.163.26:9113"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cloud.lhax.xyz/
        - https://matrix.lhax.xyz/health
        - https://media.lhax.xyz/
        - https://music.lhax.xyz/
        - https://paper.lhax.xyz/
        - https://status.lhax.xyz/
        - https://rss.lhax.xyz/
        - https://znc.lhax.xyz/
        - https://lhax.xyz/
        - https://leongr.nl/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "synapse"
    scrape_interval: 15s
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: ["matrix-synapse:8008"]

  - job_name: "pihole-exporter"
    static_configs:
      - targets: ["192.168.3.9:9617"]

  - job_name: "bind-exporter"
    static_configs:
      - targets: ["grafana-bind-exporter:9119"]

  - job_name: OpenWrt
    static_configs:
      - targets: ["192.168.3.1:9100"]

  - job_name: "loki"
    scrape_interval: 5s
    static_configs:
      - targets: ["loki:3100"]

  - job_name: matrix-sliding-sync-proxy-exporter
    scheme: https
    tls_config:
      ca_file: /ca.crt
    static_configs:
      - targets: ["matrix-sliding-sync-proxy-exporter.internal"]
