global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cloud.lhax.xyz:1234/
        # - https://cloud.lhax.xyz:9396/
        # - https://status.lhax.xyz:1234/
        - https://192.168.3.9:9396/
        - https://lhax.xyz/
        - https://leongr.nl/
        - https://concertrack.com/
        - http://grafana:3000
        - http://nginx-proxy-manager:81
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
