modules:
  http_2xx:
    prober: http
    http:
      # valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      # method: GET
      # fail_if_no_ssl: true
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: true
  tcp_connect:
    prober: tcp
