version: "3"

services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:1.21.2
    restart: unless-stopped
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
