version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.19.6
    restart: unless-stopped
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
